name: Shali
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14134
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f9ad9f'
    - '#124273'
    - '#846992'
    - '#dc2134'
  brandStrength: 0.625
  lightness: 0.777686626650393
  saturation: 0.7098368634469807
  rhythmicContrast: 0.8236328468192369
purpose: []
