name: Shali
favicon: null
layout_spectrum: 0.25527
typography_spectrum: 0.27379
title: My love
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#dcc9b8'
    - '#ad9e49'
    - '#222512'
    - '#5a5126'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
