name: Shali
favicon: null
layout_spectrum: 0.9388670907355845
typography_spectrum: 0.9444737478625029
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6217702343128622
  lightness: 0.777686626650393
  saturation: 0.7098368634469807
  rhythmicContrast: 0.8236328468192369
purpose: []
